# See https://pre-commit.ci for more information
ci:
  autofix_prs: true
  autofix_commit_msg: 'pre-commit.ci auto-fixes'
  autoupdate_schedule: weekly
  autoupdate_commit_msg: 'pre-commit.ci: auto-update hooks'

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-shebang-scripts-are-executable
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
    -   id: codespell
        args: [-w]
-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
    -   id: shellcheck
        args: [-x, -e, SC2015]
-   repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.12.0-2
    hooks:
    -   id: shfmt
        args: [-w, -i, '2']
